version: 1.0.{build}

platform:
  - x64

install:
  - cmd: echo "Install OpenCV..."

build_script:
  - cmd: cmake --version
  - cmd: php -v

environment:
  BIN_SDK_VER: 2.1.2 # 定义php-sdk-binary-tools 版本
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH: x64
      VC: vc15
      PHP_VER: 7.2.3
      TS: 0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH: x64
      VC: vc15
      PHP_VER: 7.2.3
      TS: 1